### ISSUE TITLE
Not Centering

### ISSUE THREAD

**Issue by magicman86** [alehandrof/Typewriter#6]
Worse on a Mac than you think. It won't start centering until after you have a SCREEN FULL of text. Not just a half-screen like in Windows. Behaves differently as well. I have to fill your screen buffer and then manually place my cursor in the middle, and SOMETIMES it picks up what I'm doing and does the typewriter thing. Not as you have described in your last post. Close this if you want, but please be sure to mark this as not compatible with OSX.

**Comment by fgimian** [comment]
This thread helped me too (I'm also on OS X) and now the plugin is working, yay! 😄 

Is there any way to make it center from the very top of the document (similar to certain Markdown editors) or is this simply not possible due to Sublime plugin API limitations .etc?

**Comment by alehandrof** [comment]
@fgimian Not that I know of.

Also, I'm closing this issue, as it was resolved by 7405af45c02c7fadaf5dd0523f7ea44b1c0d8c7f.
