### ISSUE TITLE
How to set it up only for markdown files

### ISSUE THREAD

**Issue by ricardoa-vega-stori** [alehandrof/Typewriter#8]
Hello there, thanks for creating this plugin.

I was wondering if there's a way to activate it automatically for markdown files. I mean, instead of firing up Ctrl+Shift+P and selecting the typewriter mode, having it automatically loaded when a file like Markdown is opened.

I my ST3 customized for .md extension and it would be great if there's a way to call the plugin via the settings for that particular extension.

Thanks in advance.

**Comment by alehandrof** [comment]
As mentioned in the README, you can enable Typewriter Scrolling using the `"typewriter_mode_scrolling" : true,` setting. You can put this in any syntax or project file. I have it in my Distraction Free settings.

Unfortunately, you can't do the same with the Typewriter Typing mode. That has to be enabled via a command.

**Comment by ricardoa-vega-stori** [comment]
Alright, thank you. It doesn't matter, I really like the plugin :)
